### 결제 요청(포인트)
POST {{commerce-api}}/api/v1/payments
X-USER-ID: user000001
Content-Type: application/json

{
  "orderId": 1,
  "paymentType": "POINT",
  "cardType": "",
  "cardNo": "",
  "amount" : 5000
}

### 결제 요청(카드)
POST {{commerce-api}}/api/v1/payments
X-USER-ID: user000001
Content-Type: application/json

{
  "orderId": 1,
  "paymentType": "CREDIT_CARD",
  "cardType": "SAMSUNG",
  "cardNo": "1234-5678-9814-1451",
  "amount" : 5000
}
