### 포인트 충전
POST {{commerce-api}}/api/v1/points/charge
X-USER-ID: user000001
Content-Type: application/json

{
  "amount": 100000000
}

### 포인트 조회
GET {{commerce-api}}/api/v1/points
X-USER-ID: user000001


