spring:
  application:
    name: commerce-batch
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - logging.yml
      - monitoring.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always



---
spring:
  config:
    activate:
      on-profile: local, test

datasource:
  mysql-jpa:
    main:
      jdbc-url: jdbc:mysql://localhost:3306/loopers
      username: application
      password: application